source $OMZ/lib/omz.sh
source $OMZ/plugins/z.lua/z.lua.plugin.zsh
source $OMZ/plugins/extract/extract.plugin.zsh
source $OMZ/plugins/fzf-tab/fzf-tab.zsh
source $OMZ/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $OMZ/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $OMZ/plugins/vi-mode/vi-mode.plugin.zsh
source $OMZ/plugins/sudo/sudo.plugin.zsh
source $OMZ/plugins/command-not-found/command-not-found.plugin.zsh
source $OMZ/plugins/hitokoto/hitokoto.plugin.zsh
